// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static String _env(String key, String fallback) =>
      dotenv.maybeGet(key) ?? fallback;

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _env('FIREBASE_ANDROID_API_KEY',
            'AIzaSyAnv-FhL1RfZtIpNgLxIphieoeQMa1YHWQ'),
        appId: _env('FIREBASE_ANDROID_APP_ID',
            '1:168218307114:android:ff752f478c0d59c93bb153'),
        messagingSenderId:
            _env('FIREBASE_ANDROID_MESSAGING_SENDER_ID', '168218307114'),
        projectId: _env('FIREBASE_ANDROID_PROJECT_ID', 'rudhiraksh-fcm'),
        storageBucket: _env('FIREBASE_ANDROID_STORAGE_BUCKET',
            'rudhiraksh-fcm.firebasestorage.app'),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _env('FIREBASE_IOS_API_KEY',
            'AIzaSyARaRV-Z3JtoreHdvEX8PQnNnKgNGH6K9U'),
        appId: _env(
            'FIREBASE_IOS_APP_ID', '1:168218307114:ios:08224f4a66ef00f03bb153'),
        messagingSenderId:
            _env('FIREBASE_IOS_MESSAGING_SENDER_ID', '168218307114'),
        projectId: _env('FIREBASE_IOS_PROJECT_ID', 'rudhiraksh-fcm'),
        storageBucket: _env('FIREBASE_IOS_STORAGE_BUCKET',
            'rudhiraksh-fcm.firebasestorage.app'),
        iosBundleId:
            _env('FIREBASE_IOS_BUNDLE_ID', 'com.rudhiraksh.rudhirakshapp'),
      );
}
